### ISSUE TITLE
Auto Upload Mapping

### ISSUE THREAD

**Issue by anmoljain10** [nuxt-modules/cloudinary#100]
Is it possible to set auto-upload mapping for the local environment? If we add a new image and use the cld-image component, the image is not uploaded to cloudinary. Is there a way we can do it locally? Since if we have to make any changes to the image we'll do it on development environment only.

**Comment by mayashavin** [comment]
@anmoljain10 Hi, you can try to use the server functionality `upload`, we have an example of doing [this auto-upload mapping with Nuxt-content](https://cloudinary.nuxtjs.org/integrations). The idea is similar. You can use Nuxt hooks to intercept and auto upload the local images to cloudinary. Let me know if it works.

**Comment by anmoljain10** [comment]
Thanks! I'll check this out

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
