### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by Gyurmatag** [nuxt-modules/cloudinary#107]
Hi!

When this will be compatible with Nuxt3?

**Comment by talaxasy** [comment]
I want to know too

**Comment by flozero** [comment]
Is it still something people are interested to have ? If yes I may take time to do the migration if you are good with that @mayashavin

**Comment by mayashavin** [comment]
@flozero if you have to help, I'd love it. I just don't find any time for this migration at the moment :(

**Comment by flozero** [comment]
Alright will try to find some times to work on it as I am using cloudinary on my nxut3. projects

**Comment by Baroshem** [comment]
Hey folks,

I had a call recently with @colbyfayock and I will be working on migrating the module to Vue/Nuxt 3 version in the upcoming weeks :)

Stay tuned! 🚀
