### ISSUE TITLE
Warn when invalid configuraiton

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#116]
### Is your feature request related to a problem? Please describe.
I accidentally copied the wrong .env value and the image just simply didn't load.

Would it make sense to include warning you're missing the environment variable so its an easy assist for someone trying to get started?

### Describe the solution you'd like

Maybe a `console.warn` if the Cloud Name isn't found, meaning its not set.

### Describe alternatives you've considered

A thrown error might be too much, but broken images could be considered a breaking feature 🤷

**Comment by Baroshem** [comment]
Added in https://github.com/nuxt-modules/cloudinary/commit/0a3a78e6d821f77ab3fc48a3783cc90e212b354a
