### ISSUE TITLE
Required props: alt, width, height

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#117]
### Is your feature request related to a problem? Please describe.

Pretty common pattern across the industry for image components is to require a width, height, and alt attribute.

- Width and height help to let the browser understand the area that the image is going to take. This is especially important when it comes to layout shift, which provides a bad user experience, and actually will penalize your app
- Alt text is great to help push accessibility, which isn't a web requirement, but is a really great thing to promote as critical to image placement. Someone can simply do `alt=""` if they dont have one.

### Describe the solution you'd like

i'm not sure what Nuxt patterns are for required props. not having a `src` 500's.

### Describe alternatives you've considered

These aren't things required to make an image work but promoting these as best practices are critical to building a better web, making it easier for people to opt-in to better patterns for better user experience and accessibility.

**Comment by colbyfayock** [comment]
Layout shift example without size attributes

![ezgif com-resize](https://github.com/nuxt-modules/cloudinary/assets/1045274/382cd455-8c1c-4f6b-99be-19fc4b91680a)

**Comment by Baroshem** [comment]
Added in https://github.com/nuxt-modules/cloudinary/commit/9be462289d4eb00d33555acb6fe2e0697f6f30fe
