### ISSUE TITLE
Responsive sizing via `sizes` prop not working

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#120]
Using the `sizes` prop creates different srcset sizes but it does not produce appropriate Cloudinary URLs for each size

### Version

@nuxtjs/cloudinary 2.0.0-rc.3
nuxt: 3.5.2

### Steps to reproduce

```
<CldImage
      src="images/turtle"
      width="600"
      height="600"
      crop="fill"
      sizes="sm:100vw md:50vw lg:400px"
    />
```

Sizes syntax example pulled from: https://image.nuxtjs.org/components/nuxt-img#sizes

### What is Expected?

Each URL should include a width resize transformation that corresponds to the srcset size

### What is actually happening?

Srcset includes all the same images for each size

```
srcset="
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 384w,
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 400w,
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 640w,
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 768w,
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 800w,
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/c_fill,w_600,h_600,g_auto/f_auto/q_auto/v1/images/turtle?_a=E 1280w
"
```

**Comment by colbyfayock** [comment]
if the Nuxt Image module doesn't allow for any type of custom configuration for constructing the src based on the responsive sizing and props, might want to consider using Unpic which makes this pretty easy

https://unpic.pics/img/vue/

```
<Image
  src="cld-sample-5"
  layout="constrained"
  width={800}
  height={600}
  alt="A lovely bath"
  transformer={({url, width, height,}) => {
    return constructCloudinaryUrl({
      options: {
        src: url,
        width,
        height
      },
      config: {
        cloud: {
          cloudName: 'example'
        }
      }
    });
  }}
/>
```

not sure how useCloudinaryUrl fits into that, if it can just sit in the `transformer` prop or not, but this is an example using the raw constructCloudinaryUrl function

**Comment by Baroshem** [comment]
I tried it with current nuxt image and also with the nuxt image rc (the newest version) but none of these versions can actually create the `sizes` properly. I think I would have to develop this functionality by myself.

**Comment by colbyfayock** [comment]
are you opposed to using Unpic? it was developed by Matt Kane, who helped build the Gatsby image component and is now working at Netlify on a lot of other things.

it will give us everything out of the box. i highly recommend **not** building this yourself
