### ISSUE TITLE
[Bug] Analytics passing in entire Nuxt package.json

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#123]
The analytics ID isn't currently applying correctly, I noticed 2 things:
- passing in a non X.X.X version (-rc1) breaks it, which is fine for development builds as its not needed
- the analytics object is passing in the entire Nuxt package.json into the configuration as opposed to just the version

Currently:

```
techVersion: nuxtPkg
```

Should be:

```
techVersion: nuxtPkg.version
```

### Version

@nuxtjs/cloudinary 2.0.0-rc.1
nuxt: 3.5.0

**Comment by colbyfayock** [comment]
i found out there's also a limitation with the techVersion property in that the API only allows a range of 1-10 for minor releases

we can just lock that to major releases and do something along the lines of:

```
okay - for the `techVersion` apparently only accepts a minor range of 1-10

so im thinking maybe what we need to do is just limit the techVersion to major

can just use something like this: 

```
`${nuxtPkg.version.split('.')[0]}.0.0`
```

honestly can do the same thing with `sdkSemver` if you think that makes sense

**Comment by Baroshem** [comment]
Fixed with https://github.com/nuxt-modules/cloudinary/commit/56c35515e89a35618d379a892646d5c115396e8b
