### ISSUE TITLE
Cloudinary Module vs Image Module 

### ISSUE THREAD

**Issue by Hebilicious** [nuxt-modules/cloudinary#127]
What would be the difference/advantages of using this module instead of the official Nuxt Image module ? 
They seem to be sharing the same scope.

**Comment by Baroshem** [comment]
Hey,

Interesting question! 

NuxtImage is a generic module and component that allows you to have optimized images and it supoorts multiple providers (by default ipx) and can use Cloudinary. But it supports only certain amount of image optimizations and transformations due to an agnostic interface.

This module however, uses the cloudinary url loader under the hood that allows for many more modifications on the actual image.

It will also come with a set of components (not yet developed but will be in upcoming weeks) such as OgImage, Widget, Upload, etc.

Let me know if that makes sense :)

**Comment by Hebilicious** [comment]
> Hey,
> 
> Interesting question!
> 
> NuxtImage is a generic module and component that allows you to have optimized images and it supoorts multiple providers (by default ipx) and can use Cloudinary. But it supports only certain amount of image optimizations and transformations due to an agnostic interface.
> 
> This module however, uses the cloudinary url loader under the hood that allows for many more modifications on the actual image.
> 
> It will also come with a set of components (not yet developed but will be in upcoming weeks) such as OgImage, Widget, Upload, etc.
> 
> Let me know if that makes sense :)

It does make sense yes. I was just wondering if you thought about joining forces and "merging" all of this work into the other module, as it feels like there's 2 official solutions (and the cloudinary docs recommend the Nuxt/Image module). Or do you think that these 2 approaches are too different ? I see that you're using unpic, and the nuxt Image module doesn't.

**Comment by Baroshem** [comment]
Yeah, I thought about that. 

I even created a PR for that ;) https://github.com/nuxt/image/pull/766

But with the Nuxt Core Team, we decided that it would be better to have a separate module with all the advanced functionality.

The unpic was suggested by Colby Fayock as Cloudinary is using it for Svelte Cloudinary as well :)

**Comment by Hebilicious** [comment]
> Yeah, I thought about that.
> 
> I even created a PR for that ;) [nuxt/image#766](https://github.com/nuxt/image/pull/766)
> 
> But with the Nuxt Core Team, we decided that it would be better to have a separate module with all the advanced functionality.
> 
> The unpic was suggested by Colby Fayock as Cloudinary is using it for Svelte Cloudinary as well :)

Haven't seen this PR and I liked this approach, so I'm surprised by the outcome. IMO the Nuxt core team needs help for managing the ecosystem (some official modules like auth are still stuck in v2). Out of curiosity, given the opportunity, would you be interested in helping maintaining and developing the Image module instead ?

**Comment by Baroshem** [comment]
The Image module is one of the core nuxt modules that are being maintained by the core team and Nuxt Labs. Contributors are open to help but more like individual contributions rather than full maintenance as in the case of smaller modules such us this one :)
