### ISSUE TITLE
Support for component passed cloud name

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#129]
### Describe the solution you'd like

I would like to recommend adding a new component prop `cloudName` that when passed will overwrite the globally registered cloud name from environment variables.

I can totally see cases where users might want to utilize fetching images from multiple cloudinary spaces. This is now possible when using the `useCldImageUrl` composable but not possible from the component perspective.

```html
<CldImage src="test" cloud-name="some-other-cloud-name" />
```

**Comment by colbyfayock** [comment]
@Baroshem maybe consider a `config` property instead, this is what we did with Next Cloudinary

the benefit here is someone can customize more things with the entire config object, which may be important if they want to set a custom cname for instance

examples:
```
config={ url: { secureDistribution: 'spacejelly.dev' } }
config={ cloud: { cloudName: 'colby' } }
```

https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters

(you wouldnt need to define these manually)

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/lib/cloudinary.ts#L53

**Comment by Baroshem** [comment]
Good idea Colby!

Will take a look at this implementation and do something similar :)
