### ISSUE TITLE
CldVideoPlayer

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#130]
### Is your feature request related to a problem? Please describe.

CldVideoPlayer is a wrapper around the Cloudinary Video Player widget.

https://cloudinary.com/documentation/cloudinary_video_player

You have two ways of loading this which I'd recommend seeing which performs better in the Nuxt context: CDN includes, npm import.

Here's the Next.js Version: https://next-cloudinary.spacejelly.dev/components/cldvideoplayer/basic-usage

The Next.js version's API is a work in progress, but my hope is to align it with the CldImage component  in the future as the options are relatively similar for what you can do. for now probably make sense just to go with the basics like i have.

As far as CDN vs import, they have different costs in how they affect page load, so it depends on what you're trying to optimize.

**Comment by Baroshem** [comment]
Done in 2.2.0
