### ISSUE TITLE
hideContextMenu property

### ISSUE THREAD

**Issue by ramzzo** [nuxt-modules/cloudinary#145]
Hi, I request you to add hideContextMenu property for video player. I wish you good work

**Comment by Baroshem** [comment]
Hey @ramzzo 

Thanks for this feature request.

Could you share more details about what you would like to achieve with it? Like what is the reasoning behind having it? Maybe there is an example in the docs or other libraries that could point me to what you are trying to achieve?

**Comment by colbyfayock** [comment]
@Baroshem does the video player currently support an options prop? If so you should be able to pass it in there. 

It's a widget configuration option. Can find it here

https://cloudinary.com/documentation/video_player_api_reference

A question I've been asking myself is which ones make sense to expose at a top level or leave in options

**Comment by ramzzo** [comment]
> Hey @ramzzo
> 
> Thanks for this feature request.
> 
> Could you share more details about what you would like to achieve with it? Like what is the reasoning behind having it? Maybe there is an example in the docs or other libraries that could point me to what you are trying to achieve?

I see the context menu in the video player as unnecessary and it breaks the design. On the other hand, the cloudinary version is written in the context menu. This removes the corporate atmosphere.

**Comment by Baroshem** [comment]
@ramzzo 

Any info from you?

**Comment by colbyfayock** [comment]
hey @Baroshem i noticed this issue when spinning up my dev locally, before opening a ticket, i just wnted to check and see if this is something on my end? wondering if it was accidentally not marked as optional: https://github.com/nuxt-modules/cloudinary/pull/148/files#diff-10a44c863aaf04f992a978372f4bdab1f4609723ec71ad640fb02f3d7a227cf4R22

<img width="804" alt="image" src="https://github.com/nuxt-modules/cloudinary/assets/1045274/0aaa4248-c041-4317-9388-7286d7f7a292">

**Comment by Baroshem** [comment]
Hey @colbyfayock. Yes, you are correct. I must have forgotten about marking this prop as optional. I will fix it in a sec
