### ISSUE TITLE
Typescript error in CldOgImage.vue

### ISSUE THREAD

**Issue by jbmolle** [nuxt-modules/cloudinary#147]
### Version

@nuxtjs/cloudinary: v2.3.2
nuxt: v3.6.5

### Steps to reproduce
Add CldOgImage to a Nuxt component / page.

### What is Expected?
It should work without any Typescript error.

### What is actually happening?
Typescript error: Property 'meta' does not exist on type 'Ref<RouteLocationNormalizedLoaded>'

**Comment by Baroshem** [comment]
Thank you @jbmolle 💚
