### ISSUE TITLE
Generative Fill: fillBackground Property 

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#151]
### Is your feature request related to a problem? Please describe.

Can we get the fillBackground property added to the project?

### Describe the solution you'd like

The fillBackground option allows the developer to use Generative Fill to extend an image.

The API options look along the lines of:
```
fillBackground // true - configures based on image width and height
fillBackground={{
  ...options
}}
```

Options include:
* crop: how to crop the image
* gravity: where to anchor the image
* prompt: to help provide context for how the fill the image

More details including how the options apply to the processing: https://cloudinary.com/blog/generative-fill-ai-powered-outpainting

The Cloudinary API is still currently in beta.

Source:
https://github.com/colbyfayock/cloudinary-util/blob/700863c02a18712e0ce01b8e7511449b21e40dc6/packages/url-loader/src/plugins/fill-background.ts#L4

And a video for how it works in Next.js: https://www.youtube.com/watch?v=2Rt5smsSp-Q

### Additional context

side note: I need to figure out a way to automate Issues or something based on maybe PRs in the core library so that we ecan synchronize updates to make sure this gets new features. But we can figure that out separately!

**Comment by Baroshem** [comment]
Released with 2.3.4 :)
