### ISSUE TITLE
Docs Overlay Props table isnt formatted correctly

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#152]
<img width="781" alt="image" src="https://github.com/nuxt-modules/cloudinary/assets/1045274/e1cf22b7-255b-4ee5-9fa2-36a18f98d6f2">

### Reproduction Link

https://cloudinary.nuxtjs.org/components/cldimage#overlay-props

**Comment by Baroshem** [comment]
Fixed in https://github.com/nuxt-modules/cloudinary/commit/1807e80f1a46feac4e78df0e6d376206c96d7748
