### ISSUE TITLE
type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.

### ISSUE THREAD

**Issue by EntertainmentPortal** [nuxt-modules/cloudinary#154]
### Version

@nuxtjs/cloudinary 2.3.4
nuxt: 3.4.3

### Steps to reproduce
installed the package, added it to nuxt.config and run 'npm run dev'.

### What is Expected?
My nuxt project should run.

### What is actually happening?
It cannot open the application, because the cloudinary components are bugging.

Straight off it is giving me these warnings/errors:

 WARN  Duplicated imports "useCldImageUrl", the one from "C:/Users/../node_modules/@nuxtjs/cloudinary/dist/runtime/composables/useCldImageUrl.d.ts" has been ignored             20:31:05  

 ERROR  [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.                                                                            20:31:06  

C:/Users/../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldOgImage.vue
77 |  };
78 |
79 |  const props = defineProps<CldOgImageProps>();
   |                            ^^^^^^^^^^^^^^^
80 |
81 |  const options = {

 ERROR  [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.                                                                            20:31:07  

C:/Users/../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldVideoPlayer.vue
63 |  };
64 |
65 |  const props = withDefaults(defineProps<CldVideoPlayerProps>(), {
   |                                         ^^^^^^^^^^^^^^^^^^^
66 |    autoPlay: "never",
67 |    controls: true,

**Comment by Baroshem** [comment]
Hey,

Could you please create a reproduction with Stackblitz?

**Comment by Baroshem** [comment]
Closing as the bug cannot be reproduced on the newer version of Nuxt
