### ISSUE TITLE
[Feature] Add a new MediaLibrary Component

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#157]
Add a new <MediaLibrary> component that will show the Cloudinary Media Library Widget

Found the Media Library Widget documentation here https://cloudinary.com/documentation/media_library_widget

Check this React examples as reference https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-ts-media-library

**Comment by AniqJaved** [comment]
@Baroshem I want to work on this issue but I wanted to ask that are we are looking to create a nuxt app which is having an implementation of Cloudinary Media Library Widget ?

**Comment by Baroshem** [comment]
Hey @AniqJaved 

The idea is to create a drop i Media compoent that users can easily import and use in their projects.

For app, you can always add an ezample in playground and docs but the general idea is to have a library :)

**Comment by R0N1n-dev** [comment]
CldMediaLibrary component broken
