### ISSUE TITLE
[Feature] Throw an error or warning in components if a cloud name is not set

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#159]
A Cloud name is required, whether set via VITE_PUBLIC_CLOUDINARY_CLOUD_NAME or via the config prop. The component should throw an error or warning in the event that it's not configured.

**Comment by FroostyCodes** [comment]
@Baroshem I would like to work on this issue

**Comment by Baroshem** [comment]
Awesome, assigning to you :)

**Comment by FroostyCodes** [comment]
@Baroshem I need some help here.
Just realized that the module.ts file already has this https://github.com/nuxt-modules/cloudinary/blob/main/src/module.ts#L37-L40

Do I need to add something else? 🤔 
Your help is really appreciated here 🙏

**Comment by Baroshem** [comment]
Hey,

You are correct. It is handled in the module configuration. Good catch 😉

And if it is not passed as component, user still needs to add it to the module configuration.

So this can be closed as completed (unintentionally 😉)
