### ISSUE TITLE
Better integration with Nuxt Image

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#163]
Can be either a full code integration or documentation section about Cloudinary module

**Comment by colbyfayock** [comment]
id love to see Nuxt Image being used under the hood to help bridge the expected experience migrating from Nuxt Image to CldImage, have they or do they intend to add a loader-like feature that will allow us to customize the URL? similar to what Next Image and Unpic provides?

**Comment by Baroshem** [comment]
I have created an issue in Nuxt Image repo to talk about it with the Core Team :)

**Comment by Baroshem** [comment]
I have created a pull request with a note about Nuxt Cloudinary in Nuxt Image documentation. I am now waiting for the maintainers to review it and merge it once ready :)

**Comment by Baroshem** [comment]
@colbyfayock 

Note about NuxtCloudinary has been merged to Nuxt Image so there should be more people coming from there for more advanced Cloudinary usage in Nuxt apps :)

**Comment by colbyfayock** [comment]
fantastic!

**Comment by Baroshem** [comment]
Closing as note in the documentation was merged and for now I think it would be safer to stick to Unpic instead of rewriting to NuxtImage (in the end, they deliver very similar functionality while it could deliver some unwanted regression bugs)
