### ISSUE TITLE
Coudinary.UploadWidget postMessage issue

### ISSUE THREAD

**Issue by cliengme** [nuxt-modules/cloudinary#165]
Version
"@nuxtjs/cloudinary": "^2.4.3",
"nuxt": "^3.8.1",

Steps to reproduce
Install module as on docs page
Tried to use CldUploadWidget component as in docs

What is Expected?
No error console and the widget to work when opening it again.

What is actually happening?
Error in the console when opening the CldUploadWidget. 
<img width="1113" alt="Capture d’écran 2023-11-21 à 17 58 47" src="https://github.com/nuxt-modules/cloudinary/assets/7067733/eb71e5b3-3314-45c8-8720-cb88bad378e9">

When the widget is closed an re-opened after uploading, it is not initiated correctly.
![Capture d’écran 2023-11-21 à 17 30 50](https://github.com/nuxt-modules/cloudinary/assets/7067733/4a6bd4b7-7220-47b6-bffe-16c360ec46ee)

I was able to fix the bug with this workaround : https://github.com/colbyfayock/next-cloudinary/compare/v4.18.0...v4.18.1

**Comment by Baroshem** [comment]
Hey Buddy,

Thanks for reporting this issue. Would you be interested in contributing? I can provide any assistance needed :)

**Comment by cliengme** [comment]
Hello, yes I can create a PR if you want.

**Comment by Baroshem** [comment]
Awesome thank you! 💚

I will review and merge it once I will be back from short vacation (~1 december)
