### ISSUE TITLE
[Feature] Update URL Loader, Update CldImage Docs

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#168]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Please update the URL Loader dependency.

Then can we port the Next Cloudinary documentation updates to this project?
- https://next.cloudinary.dev/cldimage/basic-usage
- https://next.cloudinary.dev/cldimage/configuration
- https://next.cloudinary.dev/cldimage/examples

All text can be found as markdown on GitHub:
- https://github.com/colbyfayock/next-cloudinary/tree/main/docs/pages/cldimage

Note: this may require framework-specific changes, such as removing the Next.js-specific notes and updating any syntax details that may be specific to this library.

**Comment by Baroshem** [comment]
Hey Colby,

Sure will do that later this week with a next release (probably a patch with some small bugfixes)
