### ISSUE TITLE
CldOgImage breaks typecheck

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/cloudinary#177]
### Version

@nuxtjs/cloudinary 2.5.2
nuxt: 3.9

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-5yzorc?file=.npmrc,app.vue
 

### Steps to reproduce

- run `pnpm typecheck`

### What is Expected?

- types should be ok

### What is actually happening?

- types are broken from CldOgImage

**Comment by Baroshem** [comment]
And thanks here as well 💚
