### ISSUE TITLE
/components/cldimage has a wrong url

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/cloudinary#179]
### Version

@nuxtjs/cloudinary 
nuxt: 

### Reproduction Link
https://cloudinary.nuxtjs.org/components/cldimage#configuration

### Steps to reproduce
- click on useCldImgUrl

### What is Expected?
- go to the correct page 
### What is actually happening?
- 404

**Comment by Baroshem** [comment]
Hey @huang-julien 

Thanks for the isse and the PR to fix it! 🚀
