### ISSUE TITLE
Transformer function is rendered as html attribute when mounted client-side

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/cloudinary#181]
### Version

@nuxtjs/cloudinary 2.5.2
nuxt: 3.9

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-5yzorc?file=app.vue,nuxt.config.ts,.npmrc

### Steps to reproduce
- click on toggle
- check the html of the image and see the transformer attrbute

**Comment by Baroshem** [comment]
Interesting finding @huang-julien 

Thanks for reporting it and also for finding a fix right away! 🚀
