### ISSUE TITLE
Use @cloudinary-util/types for types

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#186]

**Comment by Baroshem** [comment]
Had to reschedule working on this because I have encountered issues that stopped me from publishing a 2.6.0 version

**Comment by colbyfayock** [comment]
@Baroshem lmk if they're issues with the library and i can investigate 🕵️

**Comment by Baroshem** [comment]
Unfortunately it is a Nuxt related issue with the types. I think I need to work on updating all dependencies to the newest ones as in the new project it works as expected.

But I do appreciate the help!
