### ISSUE TITLE
[Feature] @cloudinary-util/url-loader@5.1.0

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#192]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Upgrade to @cloudinary-util/url-loader@5.1.0

Update includes:
- Adds `enhance`
- Adds `angle` as a top-level effect, also available in the effects array
- Adds `loop` as a top-level effect
- Adds a test and console warning for fill background without sizing
- Fixes `zoompan` bug with custom options

Via: https://github.com/colbyfayock/cloudinary-util/pull/145

Related changes: https://github.com/cloudinary-community/next-cloudinary/pull/448

**Comment by Baroshem** [comment]
Awesome @colbyfayock 

Thanks for this issue, I will add it in the next version :)

**Comment by Baroshem** [comment]
It was done in the recent release. Closing the issue.
