### ISSUE TITLE
[Feature] @cloudinary-util/types@1.0.1, Video Player 1.10.6

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#194]
@cloudinary-util/types was updated to 1.0.1 which simply includes a new prop to add picture-in-picture to the CldVideoPlayer

This requires an update to the Cloudinary Video Player script to 1.10.6

> This assumes that the @cloudinary-util/types has already been pulled in to manage CldVideoPlayer types, if not that's a prerequisite
> https://github.com/cloudinary-community/next-cloudinary/pull/421/files

Would be great to:
- Pull in the new type to make it available to the component
- Add an example for CldVideoPlayer that shows it in action

Related:
- https://github.com/cloudinary-community/next-cloudinary/pull/456
- https://next.cloudinary.dev/cldvideoplayer/examples#picture-in-picture

**Comment by Baroshem** [comment]
Hey Colby,

Thanks for reporting this issue. I will make sure to include it in the next release :)
