### ISSUE TITLE
type issue in CldImage

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/cloudinary#203]
### Version

@nuxtjs/cloudinary  2.5.1-2.7.0
nuxt:  3.11.1

### Reproduction Link

https://github.com/nuxt-modules/cloudinary/blob/main/src/runtime/components/CldImage.vue

### Steps to reproduce

You can run a typecheck in a project using CldImage
or
intellisense will highlight an error in https://github.com/nuxt-modules/cloudinary/blob/main/src/runtime/components/CldImage.vue
 at https://github.com/nuxt-modules/cloudinary/blob/e2d04a36b1c128027d8f6756cc70260d726610d8/src/runtime/components/CldImage.vue#L116 and  https://github.com/nuxt-modules/cloudinary/blob/e2d04a36b1c128027d8f6756cc70260d726610d8/src/runtime/components/CldImage.vue#L154

### What is Expected?

Some field values should be constrained to only  some string values

**Comment by Baroshem** [comment]
Hey Julien,

Thanks for reporting this issue. I will work on it in the upcoming days :)
