### ISSUE TITLE
Events not triggering

### ISSUE THREAD

**Issue by Kaperskyguru** [nuxt-modules/cloudinary#205]
How do I get the PublicID or Result info from the uploaded image using Nuxt 3

Here's my code

```
<CldUploadWidget
                :options="{
                  showPoweredBy: false,
                  folder: '/Get Backend Jobs/logos',
                  multiple: false,
                  sources: ['local', 'url'],
                  clientAllowedFormats: ['jpeg', 'png', 'jpg'],
                }"
                v-slot="{ open }"
                signatureEndpoint="/api/sign-cloudinary-params"
                @onSuccess="
                  (result, o) => {
                    console.log(result, o);
                  }
                "
              >
                <button
                  class="py-2 px-3 bg-blue-600 rounded text-white"
                  type="button"
                  @click="open"
                >
                  Upload an Image
                </button>
              </CldUploadWidget>
```

None of the events are triggering

**Comment by Baroshem** [comment]
Hey Buddy,

Thanks for reporting this issue. I am away from keyboard right now but will be back to you in a few hours with an answer :)

**Comment by Baroshem** [comment]
Hey,

Thanks for patience!

There was a bug in the implementation that was catching the `display-hidden` event instead of `success`. I have fixed it in 2.7.3 version.

I verified locally and in another project that following setup works:

```html
  <CldUploadWidget
    v-slot="{ open }"
    upload-preset="nuxt-cloudinary-unsigned"
    :on-upload="
      (result, w) => {
        console.log(result, w);
      }
    "
  >
```

Could you check if it works on your side?

**Comment by Kaperskyguru** [comment]
Thank you for your quick response. This was fixed

**Comment by Baroshem** [comment]
Great, closing the issue then.

If you have any issues or problems, please let us know and we will try the best we can :)
