### ISSUE TITLE
[Feature] Add config support to CldVideoPlayer, CldUploadWidget. Add global environment variables for CNAME

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#207]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Config prop for CldUploadWidget
* Config prop for CldVideoPlayer (i think this was done, but just confirming)
* Add support for global environment variables for secureDistribution and privateCdn

## **Describe the solution you'd like**
 
Like the CldImage prop, the CldUploadWidget and CldVideoPlayer should accept a config prop allowing for individual instance configuration.

The Upload Widget would allow configuration of Cloud Name and API key where the Video Player would allow Cloud Name, Secure Distribution, and Private CDN

They can all be typed as ConfigOptions which comes from the URL Loader package (similar to CldImage)

To allow configuring these at a global scale, we can add 2 environment variables, also allowing these to be enviornment dependent:

```
PUBLICPREFIX_CLOUDINARY_SECURE_DISTRIBUTION="spacejelly.dev"
PUBLICPREFIX_CLOUDINARY_PRIVATE_CDN=true
```

Here are the relevant code changes in the Next.js repo: https://github.com/cloudinary-community/next-cloudinary/pull/466

**Comment by colbyfayock** [comment]
Unsure if environment variables make as much sense given this work: https://github.com/nuxt-modules/cloudinary/issues/195

but the argument is people may have different configurations for their CNAME based on dev/prod/etc

**Comment by Baroshem** [comment]
Adding it to the scope for version 3.0.0 :)
