### ISSUE TITLE
[Feature] Use getVideoPlayerOptions to support CldVideoPlayer

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#216]
### Is your feature request related to a problem? Please describe.

getVideoPlayer options was released as a function available in the @cloudinary-util/url-loader package allowing us to maintain the logic to support the component in a shared module.

Using it is as simple as passing the options / props directly to the function, returning the options that will then be passed to the player.

```
const playerOptions = getVideoPlayerOptions(props, config);
videoPlayer(videoRef.current, playerOptions);
```

An additional argument is the `config` object, which is shaped as ConfigOptions, currently being used in the library.

Next Cloudinary: https://github.com/cloudinary-community/next-cloudinary/pull/478

Cloudinary Util: https://github.com/cloudinary-community/cloudinary-util/pull/157

**Comment by Baroshem** [comment]
Hey @colbyfayock 

Thanks for this issue. I will add it to the plan for the next RC version :)

**Comment by Baroshem** [comment]
Hey @colbyfayock 

I tried to add it to the module but I am experiencing some strange issues. Have you encountered something like this before?
<img width="875" alt="image" src="https://github.com/nuxt-modules/cloudinary/assets/37120330/6748b3fd-1c81-451e-97a3-2d6887faac8b">

**Comment by colbyfayock** [comment]
i haven't seen this before, did you try to see if it produces that error without passing it into the `videoPlayer`? or if you hardcode the cloudName into the config?

this is the code:

https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/url-loader/src/lib/video-player.ts

i'm unfamiliar with what validators-functions.js is and im not getting any results on google trying to search for it
