### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#220]
![image](https://github.com/nuxt-modules/cloudinary/assets/1045274/d6482274-0037-482c-af9a-c8360a61af5b)

Seeing an error in the console pointing to this

![image](https://github.com/nuxt-modules/cloudinary/assets/1045274/6954ae53-f161-4b46-bbca-5d273e83d9d9)

**Comment by Baroshem** [comment]
Fixed! Thanks for reporting. It was an issue with Nuxt Content and prerendering on Netlify
