### ISSUE TITLE
Missing alt field when HTML is generated

### ISSUE THREAD

**Issue by Eyap53** [nuxt-modules/cloudinary#225]
### Version

@nuxtjs/cloudinary: v3.0.0-rc.4
nuxt: v3.12.3

### Steps to reproduce

- Set up the Cloudinary module with Nuxt.
- Use the CldImage with the required fields, including the alt.
- Start the server

### What is Expected?

The HTML image generated contains an alt tag. 

### What is actually happening?

No alt is generated, which is bad for SEO.

**Comment by Baroshem** [comment]
Hey there,

Thanks for reporting this issue. I released a fix in the latest version. Could you check in 3.0.1 version? :)

**Comment by Baroshem** [comment]
Tested it few times and seems to be working. If not, please reopen the issue :)

**Comment by Eyap53** [comment]
I'm waiting for the release of 3.0.1, and I'll keep you updated ! :)

**Comment by Baroshem** [comment]
It was already published :) 

https://www.npmjs.com/package/@nuxtjs/cloudinary/v/3.0.1

**Comment by Eyap53** [comment]
Oh right, I missed it ! (I was looking at the release on the github tab).

It is working properly, thx :)

**Comment by Baroshem** [comment]
Awesome, for the patch releases, I don't publish a release note but mainly for minor and major releases :)
