### ISSUE TITLE
[Feature] Generative Replace Background

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#227]
# Feature

Add generative replace background feature to replace background using AI.

Should just need to update URL loader and get this feature. Content below to help with writing out docs.

## Usage

Replacing the background based on the image context:

```jsx copy
replaceBackground
```

Or using a string prompt:

```jsx copy
replaceBackground="fish tank"
```

Or using the object format:

```jsx copy
replaceBackground={{
  prompt: 'fish tank',
  seed: 3
}}
```

URL Loader: https://github.com/cloudinary-community/cloudinary-util/pull/167

## Example Documentation Content

https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/cldimage/configuration.mdx?plain=1#L716-L779

https://next.cloudinary.dev/cldimage/examples#generative-replace-background

**Comment by Baroshem** [comment]
Hey @colbyfayock 

I have added this feature in https://github.com/nuxt-modules/cloudinary/pull/228
