### ISSUE TITLE
[Feature] URL Loader - preserveTransformations, Util - pollForProcessing

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#229]
### Is your feature request related to a problem? Please describe.

`preserveTransformations` was moved to URL Loader: https://github.com/cloudinary-community/cloudinary-util/pull/184

`pollForProcessingImage` was moved to Util https://github.com/cloudinary-community/cloudinary-util/pull/187

This should allow us to remove this code from the frameworks

Ex: https://github.com/cloudinary-community/next-cloudinary/pull/504

**Comment by Baroshem** [comment]
Great initiative, will plan to have it as a part of next version :)
