### ISSUE TITLE
[Feature] Coordinates-based Cropping

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#230]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add support for coordinates-based cropping.

```
crop={{
  type: 'crop',
  width: 400,
  height: 400,
  x: 80,
  y: 350,
  gravity: 'north_east',
  source: true
}}
```

change is available inside of @cloudinary-util/url-loader@5.10.0, should just need to update documentation and add an example as it makes sense.

https://github.com/cloudinary-community/next-cloudinary/pull/509
https://next.cloudinary.dev/cldimage/examples#cropping

**Comment by nooras** [comment]
hey @colbyfayock  @Baroshem 
I am interested in this task. Can you please assign me?
Also it would be great if you guys can provide more details and examples.

**Comment by Baroshem** [comment]
Hey there @nooras 

Yes, feel free to grab it! What you see when running the project is ok. It is a playground of all modules features. Feel free to comment the ones that you dont need and work only on the ones related to the issue :)

**Comment by nooras** [comment]
> Hey there [@nooras](https://github.com/nooras)
> 
> Yes, feel free to grab it! What you see when running the project is ok. It is a playground of all modules features. Feel free to comment the ones that you dont need and work only on the ones related to the issue :)
> 
> I dont think there are more details or examples here. Colby explained everythin pretty clear :)

I didn't get!! How to start local that it should look similar to https://cloudinary.nuxtjs.org/ ?
If I make some changes then it should reflect in local. Right? Then only I know whatever I have added its working fine!!

**Comment by Baroshem** [comment]
What you are refering to is the documentation of the module while running pnpm run dev you are runing the playground. To run the documentation you should type pnpm run docs.

But to implement it, first you would need to develop a new functionality and test it in playground and then later on add it to the documentation.

**Comment by Baroshem** [comment]
@nooras Can I do something else to help you get started?

**Comment by nooras** [comment]
> [@nooras](https://github.com/nooras) Can I do something else to help you get started?

I am still not able to see in local with pnpm run docs. Its coming like below.
![Image](https://github.com/user-attachments/assets/873d85cc-decf-4b18-ac80-fbfd338912db)

Also any docs to refer how to use playground ?

**Comment by Baroshem** [comment]
Could you check what are the errors when running the project?

For the second one, there are no docs because playground is just a simple app for testing the module components and composables. You can just add there whatever you want to test :)
