### ISSUE TITLE
Icons in the documentation do not show up (partly)

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/cloudinary#240]
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/366653f1-19c1-42bb-9cd0-091713aa3d92">

**Comment by max-arias** [comment]
Just a heads up, can't build this project without a Nuxt UI pro key, so people can't contribute

**Comment by Baroshem** [comment]
Hey, thanks for the headsup. You are entirely correct. I will remove the hacktoberfest and good first issue labels and work on it myself :)

**Comment by Baroshem** [comment]
Problem is no longer there ![Image](https://github.com/user-attachments/assets/22184dc5-c0f2-4051-aa45-ef73815c1db5)
