### ISSUE TITLE
pollForProcessingImage, Util v4

### ISSUE THREAD

**Issue by colbyfayock** [nuxt-modules/cloudinary#247]
### Is your feature request related to a problem? Please describe.

pollForProcessingImage now returns an object instead of a simple boolean. This would be considered a breaking change as the error handling may rely on that falsy response.

```
export interface PollForProcessingImageResponse {
  status: number;
  success: boolean;
  error?: string;
}
```

https://github.com/cloudinary-community/cloudinary-util/pull/213/files#diff-77ed4ecc8d07c6f02f55f6988e3c43916f9bbeea319039f9594b01820ce844f4R163-R167

the goal of that work is to provide additional context of an error, so for instance, you can log the error in development context, like this:

https://github.com/cloudinary-community/next-cloudinary/pull/553

**Comment by Baroshem** [comment]
Hey @colbyfayock thanks for reporting this feature request. If anyone is interested in developing it, please feel free to do so. If not, I will develop it end of this month to release with a new version :)
