### ISSUE TITLE
CldProductGallery not rendering

### ISSUE THREAD

**Issue by christine927t** [nuxt-modules/cloudinary#250]
I'm trying to implement `CldProductGallery` in my vue/nuxt app. I installed the latest version, added the module in my nuxt.config.js, added the CLOUDINARY_CLOUD_NAME to my .env, and added the component to my page:
 
`<CldProductGallery :media-assets="mediaAssets" />`

Then I have mediaAssets defined as:
```
const mediaAssets = [
  { tag: "wyfusw1a8h16vnigb2rj" }, // the publicId
  { tag: "e8jikhigexcfznobjorg" }
];
```
This produces a 404 error:
`GET https://res.cloudinary.com/stridek/image/list/wyfusw1a8h16vnigb2rj.json 404 (Not Found)`

So then I switched the mediaAssets property to publicId instead of tag:
```
const mediaAssets = [
  { publicId: "wyfusw1a8h16vnigb2rj" }, // by default mediaType: "image"
  { publicId: "e8jikhigexcfznobjorg" }
];
```
The original 404 is gone but now I get this error and nothing is rendered:
```
index.jsx:159 Uncaught (in promise) Error: Element is probably not rendered to the DOM - something with your layout or CSS definition
    at Re.render (index.jsx:159:13)
```
I'm not sure what element this error is referring to. If anyone can help I'd greatly appreciate it.

**Comment by christine927t** [comment]
I figured out it was an issue with the page not being mounted when `CldProductGallery` was trying to find the element on the page. I added a conditional v-if variable to the CldProductGallery component so it will only attempt to be rendered once the page is ready and now it's rendering.

**Comment by Baroshem** [comment]
Hey there!

I didnt make it to help you in time but I am happy that you have found a way sooner!

Happy coding :)
