### ISSUE TITLE
CldProductGallery - updating mediaAssets

### ISSUE THREAD

**Issue by christine927t** [nuxt-modules/cloudinary#252]
What is the correct syntax for updating mediaAssets on the fly?
The scenario is that I have one set of mediaAsset images loaded in my CldProductGallery and I want a click event the user makes to update the images in the mediaAssets array and display the new images in the CldProductGallery. 

thank you!

**Comment by Baroshem** [comment]
Hey,

I would recommend trying to make `mediaAssets` reactive `ref` or `computed` properties.

I dont know what is the user trigger but let's say that it is a button so after clicking the button @click we set value of certain `ref` variable to something and in a `watch` we are watching over this button state and based on it, we are modyfing the mediaAssets property that makes the component rebuild. It can probably also be done in a computed property only but I wasn't sure what exactly is the scenario here.

I don't know the exact use case so I am using some sort of pseudocode here :)

**Comment by christine927t** [comment]
Hey, yeah thanks that makes sense! I did make mediaAssets a ref and had to add a key on the CldProductGallery component to make it re-render. That ended up working fine. 
I have a regular function that’s updating mediaAssets on button click (and the data was updating) but that wasn’t enough to make a component re-render. 
I like your idea of using a watcher or computed property better though so I will have to update my code and try that next week! 
Thanks for your help!
