### ISSUE TITLE
Allow server-side uploads from the client by proxying the request

### ISSUE THREAD

**Issue by syropian** [nuxt-modules/cloudinary#27]
Since universal apps still run on a lightweight server, it'd be great if we could server-upload images from the client by proxying the upload request. This would allow adding features like user-uploaded content to Nuxt apps with minimal configuration!

**Comment by mayashavin** [comment]
@Atinux I'm already on it :)

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
