### ISSUE TITLE
Using with Nuxt Storybook throw error: fs is not found

### ISSUE THREAD

**Issue by mayashavin** [nuxt-modules/cloudinary#44]
Bug:
`fs` is supposed to be only on server-side (nodejs module), yet when using Storybook with Cloudinary, it throw compiling error as below

<img width="1225" alt="Screen Shot 2020-11-18 at 10 29 39" src="https://user-images.githubusercontent.com/6650139/99505234-3ddbb780-2989-11eb-93d1-8367db0a74e9.png">

**Comment by paulwag** [comment]
Running into the same issue .. have you been able to figure out how to get around this error?

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
