### ISSUE TITLE
Trouble with SSR

### ISSUE THREAD

**Issue by madsh93** [nuxt-modules/cloudinary#52]
Hi

I have just installed this module and testing it out. One thing I am confused about - is this module SSR ready?

e.g. using <cld-image> is only rendered client-side.

**Comment by mayashavin** [comment]
@madsh93 Nuxt is SSR, so this module is for both SSR and static site generating. 
> e.g. using is only rendered client-side.
I don't quite understand. Can you please elaborate a bit?

**Comment by madsh93** [comment]
@mayashavin Hi Maya

Sorry for the short explanation. My issue is, when I add the module and do the <cld-image>, the image works great, but it is not displayed when javascript is blocked, therefore I assume it does not work with SSR?

**Comment by mayashavin** [comment]
@madsh93 Got it. The current version for components used in this module has a problem with SSR afaik, it rendered 'cld-image' in the html page instead of the actual img tag in SSR. The next version of the Vue components has the fixes for it, and I'm waiting for its release to fully test.

I will suggest to use `$image.url` for now if you want it to work when javascript is blocked.

Will keep this issue open and update it :). Hope it helps.

And thanks a lot for reporting it :)

**Comment by mayashavin** [comment]
@Clex1o1 all the versions currently, including the latest - `v1.0.3-beta-2`.

**Comment by madsh93** [comment]
@mayashavin Hey Maya. Is this planned for Nuxt 3.0 or 2.15? :-)

**Comment by mayashavin** [comment]
@madsh93 currently it's planned for 2.15. But I try to make it compatible with Vue 3x (aka Nuxt 3) if we can't release it before end of March :)

**Comment by tomiiide** [comment]
@mayashavin How's it going? Any update on this?

**Comment by finex** [comment]
Hi, does this mean that if I generate a nuxt.js website using the static target the `cld-image` tag does not work?

**Comment by johncastorina** [comment]
Hello, any updates? REALLY need this to be working SSR.

**Comment by kissu** [comment]
@johncastorina maybe give a look to `nuxt/image` and see if it works there: https://image.nuxtjs.org/providers/cloudinary

**Comment by dosstx** [comment]
I am new to this module...just discovered the SSR issue too.

**Comment by haykkh** [comment]
I wrapped the `<cld-` components in `<client-only>` for now. Any potential downsides to this?

**Comment by kissu** [comment]
@haykkh the image will not be available on server side.

**Comment by haykkh** [comment]
@kissu SSR doesn't work so the image isn't available server side anyway though, right?

**Comment by kissu** [comment]
Indeed.

**Comment by muhammedjenos** [comment]
This is still not resolved? Getting a lot of errors about "The client-side rendered virtual DOM tree is not matching server-rendered content" when using with Nuxt 2.15.7 and cloudinary 1.0.3. 

Any update?

**Comment by Baroshem** [comment]
Hey, Closing this as it targets the v1 version and it is a really old issue

**Comment by kissu** [comment]
This one may be helpful too: https://v1.image.nuxtjs.org/providers/cloudinary
