### ISSUE TITLE
Endpoint for deleting file on Cloudinary

### ISSUE THREAD

**Issue by YannFroment** [nuxt-modules/cloudinary#55]
Hi :)

I don't find in documentation the endpoint for deleting an uploaded file on Cloudinary.

According to Cloudinary API, it should be like `Cloudinary::Uploader.destroy(public_id, options = {})`

But $cloudinary instance doesn't have a destroy method.

Thanks for your work and your attention <3

KR

**Comment by mayashavin** [comment]
@YannFroment Thank you for reporting.
This API is not yet provided by this module. Currently we only have `upload` and `explicit` exposed. I'm considering this as one of the next version features :).

**Comment by YannFroment** [comment]
Thanks a lot Maya ! :)

**Comment by dosstx** [comment]
Hi I am new to cloudinary/nuxt module. Just to confirm, there is no way to delete a cloudinary hosted image through this module, correct?

If not, then is there a process for deleting these images in general?
