### ISSUE TITLE
Where to find $cloudinary.image.url options details

### ISSUE THREAD

**Issue by iwgx** [nuxt-modules/cloudinary#64]
Hi, thanks for this great module!

I'm new to Cloudinary, and I want to know what I can pass as second argument to `$cloudinary.image.url('path-to-image', {})`
Some example in the docs highlight few of them, but I want to know all possibility I can do.

May I know where I can found that? And is that possible to add them to docs too?

Maybe like, `For options object you can find details here` or so.
Thanks again

**Comment by mayashavin** [comment]
@iwgx this is a reference for the current api of `options` to pass - https://cloudinary.com/documentation/javascript_image_manipulation#apply_common_image_transformations_using_javascript

And yes, we should add it in the docs :). If you want to contribute a PR, I'm more than happy to review.

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
