### ISSUE TITLE
Question: How do I access cloudinary inside the express server? (Nuxt+ TS + Express Setup)

### ISSUE THREAD

**Issue by ShubhamVerma1811** [nuxt-modules/cloudinary#75]
Hey,
My setup is Nuxt with TS and Express as the server middleware.

I read the docs and searched a lot but couldn't find the way to access the cloudinary module server side.
The docs says `context..$cloudinary` and `this.$cloudinary`, tried both didn't work.

Also tried  `{ServerAPI} from '@nuxtjs/cloudinary`, didn't work.

So finally I am asking here.
Any help is appreciated.
Thanks.

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
