### ISSUE TITLE
Fetch by tag or all images

### ISSUE THREAD

**Issue by sandro-git** [nuxt-modules/cloudinary#87]
Hello , 

i'm don't find a way to get all images from my cloudinary by tag. maybe i'm missing somthing ?

**Comment by nawalnew** [comment]
Searching for the same. Please tell me if you find a Solution @sandro-git . I will tell you mine if I find one.

**Comment by nawalnew** [comment]
I have a Solution / Workaround for this. 
Working with Tags. Just replace it with your name.


```javascript
<template>
  <div class="px-12 md:px-48 ">
    
    <div v-for="post of posts">
      <cld-image :public-id="post.public_id" responsive loading="lazy" />
    </div>
    
</div>
  
</template>

<script>

export default {
  data() {
    return {
      posts: []
    }
  },

  methods: {
    async refresh() {
      const list = await this.$axios.$get('https://res.cloudinary.com/YOUR-ACCOUNT-NAME/image/list/YOUR-TAG-NAME.json')
      this.posts = list.resources
    }

  }
}
</script>
```

**Comment by sandro-git** [comment]
i was inspired with your solution and i come to this one which doesn't need button i think he is reactive.
`async asyncData({ $axios }) {
    const images = await $axios.$get(
      'https://res.cloudinary.com/vr-cafe/image/list/Jeux.json'
    )
    return { images }
  },

  computed: {
    imageComputed() {
      return this.images.resources.map((image) => {
        return this.$cloudinary.image.url(image.public_id)
      })
    },
  },

**Comment by sandro-git** [comment]
sorry i'm not fluent in making pretty code in github. ;)

**Comment by nawalnew** [comment]
@sandro-git 
Nice Solution. I am still struggling get the Additional Metadata or Tags from the Cloudinary API. 

Thats why I needed a Refresh button for testing. But implemented now your Solution :) 
Happy Coding

**Comment by sandro-git** [comment]
It’s my next step getting metadata. I let you know when I get it. Thanks for helping me. It’s good to help each other. Happy coding too.

**Comment by YoavBadt** [comment]
i dont understand. 
if i have the url in order to put it into 
```
async function () {
const images = await this.$cloudinary.image.url('url' <----here!)
this.data = images
}
```
then why would I need this module? for transformations? 
i dont get it. 
i NEED the to fetch url, if i have the url why would i fetch it. 
i need all the urls of all my images. 
thats the whole point. 

in the gridsome version of this module you can just ask using graphql for all the images that contain a word (like a folder name) in their public_id. 
why cant this be achieved in nuxt? 
i need to pass a varaible with a folder name into the the async function. 

this is boggling me.

**Comment by YoavBadt** [comment]
has anyone found a way to get all the urls in cloudinary with this module? 
the gridsome version of this plugin allows to do this very simply. 
is it not possible in Nuxt?

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
