### ISSUE TITLE
Nuxt3 options not defined

### ISSUE THREAD

**Issue by jhull** [nuxt-modules/cloudinary#92]
Is this module compatible with Nuxt 3?

Using same setup from before I'm now getting this:

```
 ERROR  Cannot start nuxt:  options is not defined                                                                 19:37:03

  at eval (eval at <anonymous> (node_modules/lodash.template/index.js:1550:12), <anonymous>:9:26)
  at compileTemplate (node_modules/@nuxt/kit/dist/index.mjs:952:45)
  at async node_modules/nuxt3/dist/index.mjs:940:22
  at async Promise.all (index 11)
  at async generateApp (node_modules/nuxt3/dist/index.mjs:939:3)
  at async build (node_modules/nuxt3/dist/index.mjs:977:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6763:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6793:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:417:7)

```

**Comment by eMeRiKa13** [comment]
Same question as @Zielgestalt!

I'm looking for a Nuxt3 compatible service to resize images.

**Comment by dosstx** [comment]
Anyone successfully using this with Nuxt3?

**Comment by mayashavin** [comment]
@Zielgestalt @eMeRiKa13 @dosstx I'm planning to have this taken care in next month. Meanwhile if you want to resize images using Cloudinary, there are two options - one is using nuxt-image with cloudinary as the provider :), or [Cloudinary URL Builder](https://cloudinary-build-url.netlify.app/) for optimized and lighter weight package to build image urls :). Let me know if those work for you

**Comment by Zielgestalt** [comment]
@mayashavin thanks! Great news!
I think nuxt-image isn't nuxt3 ready, too. But I will give the URL builder a try. Thanks!

**Comment by dosstx** [comment]
@mayashavin Thanks for the update! I am moving to Nuxt3 now and discovered that the Nuxt Image module is not yet ready for Nuxt3 (though, I understand it is close to being ready). So, we may have 3 options soon: 1.)  Nuxt Image 2.) Cloudinary URL builder 3.) Nuxt Cloudinary module 

Note: I was using the cloudinary API with Nuxt 2 to delete images and invalidate old caches -- not sure yet how that will work with Nuxt3.

**Comment by kissu** [comment]
What are the differences with https://github.com/cloudinary/js-url-gen and https://github.com/cloudinary/frontend-frameworks?
It looks like there is a lot of various SDK all over the place. 😅

**Comment by Gyurmatag** [comment]
When will this library be ready for Nuxt3?

**Comment by dosstx** [comment]
Hi all, 
 just a related update -- the Nuxt Image Module is now compatible with Nuxt 3. This is another option for integrating Cloudinary with Nuxt3: https://v1.image.nuxtjs.org/getting-started/installation

**Comment by mayashavin** [comment]
> What are the differences with https://github.com/cloudinary/js-url-gen and https://github.com/cloudinary/frontend-frameworks? It looks like there is a lot of various SDK all over the place. 😅

depends on what you want to use, these are the new version developed by the SDK team of Cloudinary. If you only want to generate the url for your images then I will suggest to use cloudinary-build-url

**Comment by mayashavin** [comment]
> When will this library be ready for Nuxt3?

Hopefully soon. I have no free time to look into it yet :(

**Comment by Baroshem** [comment]
Good news guys,

A brand new Nuxt 3 version of this module is out for you to test out!

I will close this issue as it is probably out of date.

Please open new issues for the features you would like to see in the stable 2.0.0 version :)

**Comment by kissu** [comment]
Also, give a try to that one: https://v1.image.nuxtjs.org/providers/cloudinary
