### ISSUE TITLE
HTML Validation Error: Unknown element <cld-image>  

### ISSUE THREAD

**Issue by dosstx** [nuxt-modules/cloudinary#93]
When using this module in NuxtjS2, I get the following HTML validation error when using the `cld-image` element:

```
Unknown element <cld-image>  
```
I am using it like so:

```
              <cld-image
                :public-id="post.photoURL"
                class="rounded-circle me-1"
                type="fetch"
                width="40"
                height="40"
                crop="fill"
                gravity="auto"
                :alt="`${post.displayName}'s avatar image`"
              ></cld-image>
```

The app works, just that I get the above warning in my validator. Any advice on how to fix?

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
