### ISSUE TITLE
nuxt cloudinary module vs gridsome version of the module

### ISSUE THREAD

**Issue by YoavBadt** [nuxt-modules/cloudinary#98]
hey !
in the gridsome-source-cloudinary version of this module it is possbile to do this in pages and also in the gridsome.server.js, 
 : 

allCldMedia(filter: { public_id : { regex:"Art"} }) {
  edges {
    node {
     public_id
      secure_url
      }
     }
   }
        
(i have a folder in cloudinary called "art" so the word "art" apears in the pudblic_id string of all the images in the folder)
how can i achieve this in the nuxt version of the module? doesnt matter if in the pages or "store"...or somwhere
thanks!

**Comment by mayashavin** [comment]
@YoavBadt it might be a bit late (I don't know why I don't receive any Github notifications :( ). If you are looking for a way to search for a specific folder, currently we don't have it supported out-of-the-box yet. You need to use cloudinary Node SDK to perform that action. I will try to add the support in the next release :)

**Comment by Baroshem** [comment]
Hey, I am closing this issue as it is targeting the v1 version and it is really old (more than one year stale)
